name: Clean History
on: push
jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          git checkout --orphan new-branch
          git add -A
          git commit -m "Initial commit (cleaned history)"
          git branch -D main
          git branch -m main
          git push -f origin main
